function chans = dialog_deleter(chans)
f = figure('Units','Normalized',...
'Position',[.4 .4 .2 .2],...
'NumberTitle','off',...
'Name','Delete Channels','MenuBar','None');
e1 = uicontrol('Style','Listbox',...
'Units','Normalized',...
'Position',[.6 .3 .3 .6],...
'Tag','mylist','Max',247,'Min',0,...
'String',chans);
t1 = uicontrol('Style','Text',...
'Units','Normalized',...
'Position',[.1 .3 .3 .6],...
'Tag','myedit','String','Select channels to delete');
p = uicontrol('Style','PushButton',...
'Units','Normalized',...
'Position',[.6 .1 .2 .1],...
'String','OK',...
'CallBack','uiresume(gcbf)');
uiwait(f)
chans = {chans{get(e1,'Value')}};
close(f)