function settings = dialog_epocher(types)

% main function
h.f = figure('Units','Normalized',...
'Position',[.4 .4 .2 .2],...
'NumberTitle','off',...
'Name','Epoch Definition','MenuBar','None');
h.e1 = uicontrol('Style','Listbox',...
'Units','Normalized',...
'Position',[.55 .3 .4 .6],...
'Tag','mylist',...
'String',types);
h.lc = uicontrol('Style','Edit',...
'Units','Normalized',...
'Position',[.05 .7 .2 .2],...
'Tag','start');
h.hc = uicontrol('Style','Edit',...
'Units','Normalized',...
'Position',[.05 .5 .2 .2],...
'Tag','stop');
h.lp = uicontrol('Style','Text',...
'Units','Normalized',...
'Position',[.27 .7 .2 .1],...
'Tag','begin','String','Start');
h.hp = uicontrol('Style','Text',...
'Units','Normalized',...
'Position',[.27 .5 .2 .1],...
'Tag','end','String','Stop');
h.th = uicontrol('Style','Edit',...
'Units','Normalized',...
'Position',[.05 .2 .2 .2],...
'Tag','thresh');
h.tp = uicontrol('Style','Text',...
'Units','Normalized',...
'Position',[.27 .2 .25 .1],...
'Tag','end','String','Threshold');
h.p = uicontrol('Style','PushButton',...
'Units','Normalized',...
'Position',[.6 .1 .2 .1],...
'String','OK',...
'CallBack','uiresume(gcbf)');
uiwait(h.f)
settings.start   = str2double(get(h.lc,'String'));
settings.stop    = str2double(get(h.hc,'String'));
settings.type    = types(get(h.e1,'Value'));
settings.thresh  = str2double(get(h.th,'String'));
close(h.f)
% end of main