function meg_events = dialog_events(events)

% main function
global h meg_events;
meg_events = events;
myevents = create_list(meg_events);
h.f = figure('Units','Normalized',...
'Position',[.4 .4 .2 .2],...
'NumberTitle','off',...
'Name','Select events to delete','MenuBar','None');
h.e1 = uicontrol('Style','Listbox',...
'Units','Normalized',...
'Position',[.1 .3 .8 .6],...
'Max',100,...
'Min',0,...
'Tag','mylist',...
'String',myevents,...
'CallBack',@setopts_Callback);
h.td1 = uicontrol('Style','Text',...
'Units','Normalized',...
'Position',[.1 .1 .2 .1],...
'Tag','trials','String','Selected');
h.td2 = uicontrol('Style','Text',...
'Units','Normalized',...
'Position',[.3 .1 .2 .1],...
'Tag','ntrials','String','0');
h.p = uicontrol('Style','PushButton',...
'Units','Normalized',...
'Position',[.5 .1 .2 .1],...
'String','Delete',...
'CallBack',@delete_events);
h.p = uicontrol('Style','PushButton',...
'Units','Normalized',...
'Position',[.7 .1 .2 .1],...
'String','OK',...
'CallBack','uiresume(gcbf)');
uiwait(h.f)
close(h.f)
% end of main

% subfunction to delete events
function delete_events(varargin)
global h meg_events;
val = get(h.e1,'Value');
meg_events(val) = [];
myevents = create_list(meg_events);
set(h.e1,'String',myevents);

% subfunction to set params for listbox
function myevents = create_list(meg_events)
a  = char({meg_events.mode});
b  = char({meg_events.type});
sa = size(a);
sb = size(b);
num = 1:sa(1);
num = num2str(num');
padsize = sa(2)-sb(2);
padding = repmat(' ',sa(1),padsize*3);
myevents = [num padding a padding b];

% subfunction to set dialog options
function setopts_Callback(varargin)
global h;
val = get(h.e1,'Value');
set(h.td2,'String',num2str(length(val)));