function settings = dialog_filterer

% main function
global h;
forders = {'2' '3' '4' '5' '6'};
h.f = figure('Units','Normalized',...
'Position',[.4 .4 .2 .2],...
'NumberTitle','off',...
'Name','Filter settings','MenuBar','None');
h.e1 = uicontrol('Style','Listbox',...
'Units','Normalized',...
'Position',[.6 .3 .3 .6],...
'Tag','mylist',...
'String',{'Low Pass' 'High Pass' 'Band Pass'},...
'CallBack',@setopts_Callback);
h.lc = uicontrol('Style','Edit',...
'Units','Normalized',...
'Position',[.1 .7 .2 .2],...
'Tag','lowcut');
h.hc = uicontrol('Style','Edit',...
'Units','Normalized',...
'Position',[.1 .5 .2 .2],...
'Tag','hicut');
h.lp = uicontrol('Style','Text',...
'Units','Normalized',...
'Position',[.32 .7 .2 .1],...
'Tag','lo','String','Low');
h.hp = uicontrol('Style','Text',...
'Units','Normalized',...
'Position',[.32 .5 .2 .1],...
'Tag','hi','String','Hi');
h.order = uicontrol('Style','popupmenu',...
'Units','Normalized',...
'Position',[.1 .2 .3 .2],...
'Tag','order','String',forders);
h.p = uicontrol('Style','PushButton',...
'Units','Normalized',...
'Position',[.6 .1 .2 .1],...
'String','OK',...
'CallBack','uiresume(gcbf)');
set(h.hc,'Enable','Off'); 
set(h.lc,'Enable','On');
uiwait(h.f)
settings.type  = get(h.e1,'Value');
switch settings.type
    case 1; settings.type = 'low';
    case 2; settings.type = 'high';
    case 3; settings.type = 'band';
end
settings.low   = str2double(get(h.lc,'String'));
settings.high  = str2double(get(h.hc,'String'));
settings.order = str2double(char(forders(get(h.order,'Value'))));
close(h.f)
% end of main

% subfunction to set dialog options
function setopts_Callback(varargin)
global h;
val = get(h.e1,'Value');
switch val
    case 1; set(h.hc,'Enable','Off'); set(h.lc,'Enable','On');
    case 2; set(h.hc,'Enable','On');  set(h.lc,'Enable','Off');
    case 3; set(h.hc,'Enable','On');  set(h.lc,'Enable','On');
end