function header = new_header_data(obj)

%similar to the asc_to_pdf header
header = struct( ...
    'version', uint16(1), ...
    'file_type', 'Bts', ...
	'data_format', int16(3), ... 3:float
	'acq_mode', uint16(3), ...
	'total_epochs', uint32(0), ...
	'input_epochs', uint32(0), ...
	'total_events', uint32(1), ...
	'total_fixed_events', uint32(1), ...
	'sample_period', single(1), ...
    'xaxis_label', 's', ...
	'total_processes', uint32(0), ...
	'total_chans', uint16(0), ...
	'checksum', int32(0), ...
	'total_ed_classes', uint32(0), ...
	'total_associated_files', uint16(0), ...
	'last_file_index', uint16(0), ...
	'timestamp', uint32(0), ...
	'reserved', zeros(1, 20, 'uint8'));

header = fix_checksum(obj, header);